//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yaircc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IncomingReflectionMap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IncomingReflectionMap() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yaircc.IncomingReflectionMap", typeof(IncomingReflectionMap).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InviteMessage.
        /// </summary>
        internal static string INVITE {
            get {
                return ResourceManager.GetString("INVITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JoinMessage.
        /// </summary>
        internal static string JOIN {
            get {
                return ResourceManager.GetString("JOIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KickMessage.
        /// </summary>
        internal static string KICK {
            get {
                return ResourceManager.GetString("KICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KillMessage.
        /// </summary>
        internal static string KILL {
            get {
                return ResourceManager.GetString("KILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModeMessage.
        /// </summary>
        internal static string MODE {
            get {
                return ResourceManager.GetString("MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NickMessage.
        /// </summary>
        internal static string NICK {
            get {
                return ResourceManager.GetString("NICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoticeMessage.
        /// </summary>
        internal static string NOTICE {
            get {
                return ResourceManager.GetString("NOTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartMessage.
        /// </summary>
        internal static string PART {
            get {
                return ResourceManager.GetString("PART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrivMsgMessage.
        /// </summary>
        internal static string PRIVMSG {
            get {
                return ResourceManager.GetString("PRIVMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuitMessage.
        /// </summary>
        internal static string QUIT {
            get {
                return ResourceManager.GetString("QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopicMessage.
        /// </summary>
        internal static string TOPIC {
            get {
                return ResourceManager.GetString("TOPIC", resourceCulture);
            }
        }
    }
}
