//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yaircc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageReflectionMap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageReflectionMap() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yaircc.MessageReflectionMap", typeof(MessageReflectionMap).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AwayMessage.
        /// </summary>
        internal static string away {
            get {
                return ResourceManager.GetString("away", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackMessage.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModeMessage.
        /// </summary>
        internal static string ban {
            get {
                return ResourceManager.GetString("ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModeMessage.
        /// </summary>
        internal static string dehop {
            get {
                return ResourceManager.GetString("dehop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModeMessage.
        /// </summary>
        internal static string deop {
            get {
                return ResourceManager.GetString("deop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModeMessage.
        /// </summary>
        internal static string except {
            get {
                return ResourceManager.GetString("except", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModeMessage.
        /// </summary>
        internal static string hop {
            get {
                return ResourceManager.GetString("hop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InviteMessage.
        /// </summary>
        internal static string invite {
            get {
                return ResourceManager.GetString("invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JoinMessage.
        /// </summary>
        internal static string j {
            get {
                return ResourceManager.GetString("j", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JoinMessage.
        /// </summary>
        internal static string join {
            get {
                return ResourceManager.GetString("join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KickMessage.
        /// </summary>
        internal static string kick {
            get {
                return ResourceManager.GetString("kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KnockMessage.
        /// </summary>
        internal static string knock {
            get {
                return ResourceManager.GetString("knock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartMessage.
        /// </summary>
        internal static string leave {
            get {
                return ResourceManager.GetString("leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinksMessage.
        /// </summary>
        internal static string links {
            get {
                return ResourceManager.GetString("links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListMessage.
        /// </summary>
        internal static string list {
            get {
                return ResourceManager.GetString("list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapMessage.
        /// </summary>
        internal static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrivMsgMessage.
        /// </summary>
        internal static string me {
            get {
                return ResourceManager.GetString("me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModeMessage.
        /// </summary>
        internal static string mode {
            get {
                return ResourceManager.GetString("mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOTDMessage.
        /// </summary>
        internal static string motd {
            get {
                return ResourceManager.GetString("motd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrivMsgMessage.
        /// </summary>
        internal static string msg {
            get {
                return ResourceManager.GetString("msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NamesMessage.
        /// </summary>
        internal static string names {
            get {
                return ResourceManager.GetString("names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NickMessage.
        /// </summary>
        internal static string nick {
            get {
                return ResourceManager.GetString("nick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoticeMessage.
        /// </summary>
        internal static string notice {
            get {
                return ResourceManager.GetString("notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModeMessage.
        /// </summary>
        internal static string op {
            get {
                return ResourceManager.GetString("op", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperMessage.
        /// </summary>
        internal static string oper {
            get {
                return ResourceManager.GetString("oper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartMessage.
        /// </summary>
        internal static string part {
            get {
                return ResourceManager.GetString("part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PingMessage.
        /// </summary>
        internal static string ping {
            get {
                return ResourceManager.GetString("ping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuitMessage.
        /// </summary>
        internal static string quit {
            get {
                return ResourceManager.GetString("quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatsMessage.
        /// </summary>
        internal static string stats {
            get {
                return ResourceManager.GetString("stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeMessage.
        /// </summary>
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopicMessage.
        /// </summary>
        internal static string topic {
            get {
                return ResourceManager.GetString("topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModeMessage.
        /// </summary>
        internal static string unban {
            get {
                return ResourceManager.GetString("unban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModeMessage.
        /// </summary>
        internal static string unexcept {
            get {
                return ResourceManager.GetString("unexcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserHostMessage.
        /// </summary>
        internal static string userhost {
            get {
                return ResourceManager.GetString("userhost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModeMessage.
        /// </summary>
        internal static string voice {
            get {
                return ResourceManager.GetString("voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhoMessage.
        /// </summary>
        internal static string who {
            get {
                return ResourceManager.GetString("who", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhoisMessage.
        /// </summary>
        internal static string whois {
            get {
                return ResourceManager.GetString("whois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhowasMessage.
        /// </summary>
        internal static string whowas {
            get {
                return ResourceManager.GetString("whowas", resourceCulture);
            }
        }
    }
}
