//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yaircc.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_MessageParseResults {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_MessageParseResults() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yaircc.Localisation.Strings_MessageParseResults", typeof(Strings_MessageParseResults).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &quot;ban&quot; must be run in the context of a channel..
        /// </summary>
        internal static string Ban_InvalidContext {
            get {
                return ResourceManager.GetString("Ban_InvalidContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &quot;except&quot; must be run in the context of a channel..
        /// </summary>
        internal static string Except_InvalidContext {
            get {
                return ResourceManager.GetString("Except_InvalidContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &quot;invite&quot; must be run in the context of a channel or have a channel specified..
        /// </summary>
        internal static string Invite_MissingChannel {
            get {
                return ResourceManager.GetString("Invite_MissingChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &quot;leave&quot; must be run in the context of a channel or have a channel specified..
        /// </summary>
        internal static string Leave_MissingChannel {
            get {
                return ResourceManager.GetString("Leave_MissingChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &quot;me&quot; must be run in the context of a channel..
        /// </summary>
        internal static string Me_InvalidContext {
            get {
                return ResourceManager.GetString("Me_InvalidContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &lt;action&gt;..
        /// </summary>
        internal static string MissingParameter_Action {
            get {
                return ResourceManager.GetString("MissingParameter_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing or invalid value for required parameter &lt;channel&gt;..
        /// </summary>
        internal static string MissingParameter_Channel {
            get {
                return ResourceManager.GetString("MissingParameter_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &lt;mask&gt;.
        /// </summary>
        internal static string MissingParameter_Mask {
            get {
                return ResourceManager.GetString("MissingParameter_Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &lt;message&gt;..
        /// </summary>
        internal static string MissingParameter_Message {
            get {
                return ResourceManager.GetString("MissingParameter_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &lt;nickname&gt;..
        /// </summary>
        internal static string MissingParameter_Nickname {
            get {
                return ResourceManager.GetString("MissingParameter_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter &lt;server&gt;..
        /// </summary>
        internal static string MissingParameter_Server {
            get {
                return ResourceManager.GetString("MissingParameter_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing one or more required parameters..
        /// </summary>
        internal static string MissingParameters {
            get {
                return ResourceManager.GetString("MissingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &quot;names&quot; must be run in the context of a channel or have a channel specified..
        /// </summary>
        internal static string Names_MissingChannel {
            get {
                return ResourceManager.GetString("Names_MissingChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not recognised..
        /// </summary>
        internal static string NotRecognised {
            get {
                return ResourceManager.GetString("NotRecognised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only commands can be used in the console and server tabs. Type /commands to view a list of valid commands..
        /// </summary>
        internal static string Server_InvalidMessageContext {
            get {
                return ResourceManager.GetString("Server_InvalidMessageContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for &lt;port&gt; must be numeric..
        /// </summary>
        internal static string Server_InvalidPort {
            get {
                return ResourceManager.GetString("Server_InvalidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &quot;topic&quot; must be run in the context of a channel..
        /// </summary>
        internal static string Topic_MissingChannel {
            get {
                return ResourceManager.GetString("Topic_MissingChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &quot;unban&quot; must be run in the context of a channel..
        /// </summary>
        internal static string Unban_InvalidContext {
            get {
                return ResourceManager.GetString("Unban_InvalidContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &quot;unexcept&quot; must be run in the context of a channel..
        /// </summary>
        internal static string Unexcept_InvalidContext {
            get {
                return ResourceManager.GetString("Unexcept_InvalidContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &quot;voice&quot; must be run in the context of a channel..
        /// </summary>
        internal static string Voice_InvalidContext {
            get {
                return ResourceManager.GetString("Voice_InvalidContext", resourceCulture);
            }
        }
    }
}
