//------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.0.50727.5466
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yaircc.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_Connection {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_Connection() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yaircc.Localisation.Strings_Connection", typeof(Strings_Connection).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to connect to {0}....
        /// </summary>
        internal static string AttemptingConnection {
            get {
                return ResourceManager.GetString("AttemptingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to establish a connection to {0}: {1}.
        /// </summary>
        internal static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to establish a connection to {0}: {1}. Attempting to reconnect in 15 seconds....
        /// </summary>
        internal static string ConnectionFailedRetrying {
            get {
                return ResourceManager.GetString("ConnectionFailedRetrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection to {0} has been lost. Attempting to reconnect in 15 seconds....
        /// </summary>
        internal static string ConnectionLostReconnecting {
            get {
                return ResourceManager.GetString("ConnectionLostReconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection to {0} has been terminated..
        /// </summary>
        internal static string ConnectionTerminated {
            get {
                return ResourceManager.GetString("ConnectionTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Established a connection to {0}..
        /// </summary>
        internal static string EstablishedConnection {
            get {
                return ResourceManager.GetString("EstablishedConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not connected to this server..
        /// </summary>
        internal static string NotConnectedToThisServer {
            get {
                return ResourceManager.GetString("NotConnectedToThisServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
